services:
  db:
    image: postgres:16
    container_name: studijski_program_db
    environment:
      POSTGRES_DB: studijski_program
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - studijski_program_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studijski_program"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: .
    container_name: studijski_program_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/studijski_program
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
  frontend:
    build: ./front_end
    container_name: studijski_program_frontend
    depends_on:
      - app
    ports:
      - "8081:80"

volumes:
  studijski_program_db_data:
